version: '3.5'

services:
  post-app:
    container_name: post-rest-app
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: ./post-app
    env_file:
      - "./configs/app.env"
    volumes:
      - .:/src
    ports:
      - "8080:8080"
    networks:
      - post_network
    depends_on:
      - db

  db:
    container_name: postgres
    restart: always
    image: postgres:latest
    hostname: postgres-db
    volumes:
      - ./schemes/postgres/up:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
    networks:
      - post_network

networks:
  post_network:
    driver: bridge